

-- 1 모든 도서에 대하여 도서의 도서번호, 도서명, 출판사명 출력
SELECT B.BOOKNO, B.BOOKNAME, P.PUBNAME
FROM BOOK B
    INNER JOIN PUBLISHER P ON P.PUBNO = B.PUBNO;
    
-- 2 ‘서울 출판사'에서 출간한 도서의 도서명, 저자명, 출판사명 출력 (출판사명 사용)
SELECT B.BOOKNAME, B.BOOKAUTHOR, P.PUBNAME
FROM BOOK B
    INNER JOIN PUBLISHER P ON P.PUBNO = B.PUBNO
WHERE P.PUBNAME = '서울 출판사';

-- 3 ＇정보출판사'에서 출간한 도서 중 판매된 도서의 도서명 출력 (중복된 경우 한 번만 출력) (출판사명 사용)
SELECT UNIQUE B.BOOKNAME, P.PUBNAME
FROM BOOK B
    INNER JOIN BOOKSALE BS ON BS.BOOKNO = B.BOOKNO
    INNER JOIN PUBLISHER P ON P.PUBNO = B.PUBNO
WHERE P.PUBNAME = '정보출판사';

-- 4 도서가격이 30,000원 이상인 도서를 주문한 고객의 고객명, 도서명, 도서가격, 주문수량 출력
SELECT C.CLIENTNAME, B.BOOKNAME, B.BOOKPRICE, BS.BSQTY
FROM BOOKSALE BS
    INNER JOIN BOOK B ON B.BOOKNO = BS.BOOKNO
    INNER JOIN CLIENT C ON C.CLIENTNO = BS.CLIENTNO
WHERE 30000 <= B.BOOKPRICE;

-- 5 '안드로이드 프로그래밍' 도서를 구매한 고객에 대하여 도서명, 고객명, 성별, 주소 출력 (고객명으로 오름차순 정렬)
SELECT B.BOOKNAME, C.CLIENTNAME, C.CLIENTGENDER, C.CLIENTADDRESS
FROM BOOKSALE BS
    INNER JOIN BOOK B ON B.BOOKNO = BS.BOOKNO
    INNER JOIN CLIENT C ON C.CLIENTNO = BS.CLIENTNO
WHERE B.BOOKNAME = '안드로이드 프로그래밍'
ORDER BY C.CLIENTNAME;

-- 6 ‘도서출판 강남'(publisher)에서 출간된 도서 중 판매된 도서(bookSale)에 대하여 ‘총 매출액’ 출력
SELECT P.PUBNAME, SUM(B.BOOKPRICE * BS.BSQTY) AS "총 매출액"
FROM BOOK B
    INNER JOIN BOOKSALE BS ON BS.BOOKNO = B.BOOKNO
    INNER JOIN PUBLISHER P ON P.PUBNO = B.PUBNO
WHERE P.PUBNAME = '도서출판 강남'
GROUP BY P.PUBNAME;

-- 7 ‘서울 출판사'에서 출간된 도서에 대하여 판매일, 출판사명, 도서명, 도서가격, 주문수량, 주문액 출력
SELECT BS.BSDATE, P.PUBNAME, B.BOOKNAME, B.BOOKPRICE, BS.BSQTY, 
       B.BOOKPRICE * BS.BSQTY AS "주문액"
FROM BOOK B
    INNER JOIN BOOKSALE BS ON BS.BOOKNO = B.BOOKNO
    INNER JOIN PUBLISHER P ON P.PUBNO = B.PUBNO
WHERE P.PUBNAME = '서울 출판사';

-- 8 판매된 도서에 대하여 도서별로 도서번호, 도서명, 총 주문 수량 출력
SELECT B.BOOKNO, B.BOOKNAME, SUM(BS.BSQTY) AS "총 주문수량"
FROM BOOKSALE BS
    INNER JOIN BOOK B ON B.BOOKNO = BS.BOOKNO
GROUP BY B.BOOKNO, B.BOOKNAME;

-- 9 판매된 도서에 대하여 고객별로 고객명, 총구매액 출력 ( 총구매액이 100,000원 이상인 경우만 해당)
SELECT C.CLIENTNAME, SUM(B.BOOKPRICE * BS.BSQTY) AS "총 구매액"
FROM BOOKSALE BS
    INNER JOIN BOOK B ON B.BOOKNO = BS.BOOKNO
    INNER JOIN CLIENT C ON C.CLIENTNO = BS.CLIENTNO
GROUP BY C.CLIENTNAME
HAVING 100000 <= SUM(B.BOOKPRICE * BS.BSQTY);

-- 10 판매된 도서 중 ＇도서출판 강남'에서 출간한 도서에 대하여 고객명, 주문일, 도서명, 주문수량, 출판사명 출력 (고객명으로 오름차순 정렬)
SELECT C.CLIENTNAME, BS.BSDATE, B.BOOKNAME, BS.BSQTY, P.PUBNAME
FROM BOOKSALE BS
    INNER JOIN BOOK B ON B.BOOKNO = BS.BOOKNO
    INNER JOIN CLIENT C ON C.CLIENTNO = BS.CLIENTNO
    INNER JOIN PUBLISHER P ON P.PUBNO = B.PUBNO
WHERE P.PUBNAME = '도서출판 강남'
ORDER BY C.CLIENTNAME;